version: "3.9"

services:
  worker:
    build: .
    container_name: rabbitmq_worker
    environment:
      RABBITMQ_HOST: rabbitmq  
      RABBITMQ_USER: guest
      RABBITMQ_PASS: guest
      RABBITMQ_PORT: 5672
      DOTNET_UNBUFFERED: 1
    depends_on:
      - rabbitmq
    networks:
      - rabbit_network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"     
      - "15672:15672"    
    networks:
      - rabbit_network

networks:
  rabbit_network:
    external: true
    driver: bridge
